### ISSUE TITLE
VideoChannel内Screen离线消费模式逻辑

### ISSUE THREAD

**Issue by hellojuly** [AgoraIO/Agora-Extensions#31]
VideoChannel 314行:

使用了mOnScreenConsumers.size()进行判断，导致无法进入mOffScreenConsumers循环，看起来应该是使用mOffScreenConsumers.size()。请问这个地方是bug，还是我使用姿势问题？

```
if (mOnScreenConsumers.size() > 0 || mOffScreenMode) {
    // If there is no on-screen consumers connected,
    // the off-screen consumers cannot actually be
    // called, unless the channel runs in off-screen
    // mode.
    for (IVideoConsumer consumer : mOffScreenConsumers) {
        consumer.onConsumeFrame(frame, mContext);
        makeDummySurfaceCurrent();
    }
}
```

**Comment by brianxcli** [comment]
逻辑是没错的。

离屏渲染模式是这样定义：
1） 如果当前存在 on screen consumer (即应用位于前台)，则任何 off screen consumer 都会被渲染，相当于默认 off screen mode 开启；
2） 若当前没有任何 on screen consumer (即应用位于后台)，则必须主动启用 off screen mode，允许离屏渲染。

一般来说，应用要求在位于后台时 (此时所有 on screen consumer 都会被移除) 停止后台渲染（比如隐私安全、业务逻辑设计等原因）；若允应用需要在后台离屏渲染，则必须主动开启离屏渲染

**Comment by hellojuly** [comment]
收到！是我理解错误了，看成了&操作。感谢！
